git:
    paging:
        colorArg: always
        pager: "delta --dark" # Use delta diff viewer [1][6]
        useConfig: false # Disable Git's default pager [6]
gui:
    theme:
        lightTheme: false
    mouseEvents: true
    skipDiscardChangeWarning: true
# customCommands:
#   - key: "P"
#     command: "git push --force-with-lease"
#     context: "files"
#     loadingText: "Pushing with force-with-lease..."
#     description: "force push with lease"
#
