# Install Mise:
# curl https://mise.run | sh
# Activate: Put
# eval "$(mise activate bash)" in ~/.$bashrc
# eval "$(mise activate bash)" in ~/.$bashrc
#
# mise doctor
# mise plugins ls-remote
# mise plugins ls
# mise ls
# mise ls-remote java # to see the versions
# mise use java@21
# mise use k9s
# mise prune
# mise tool aws # check info about aws
[plugins]
neovim = "https://github.com/richin13/asdf-neovim"

[tools]
###############
# Cloud
###############
aws-cli = { version = "latest", symlink_bins = "true" }
localstack = "latest"
azure-cli = "latest"
"aqua:scaleway/scaleway-cli" = "latest"

# Tools
"github:BurntSushi/ripgrep" = "latest"
"github:zyedidia/eget" = "latest"
"github:rjshrjndrn/templater" = "latest"
"github:jdx/mise" = "latest"
opencode = "latest"
starship = "latest"
"asdf:neovim" = "nightly"
go = "latest"
"aqua:schollz/croc" = "latest"
jq = "latest"
yq = "latest"
fzf = "latest"
lazygit = "latest"
btop = "latest"

###############
# k8s
###############
k9s = "latest"
stern = "latest"
kubectl = "latest"
k3d = "latest"

###############
# Container/VM
###############
lima = "latest"
podman = {version = "latest", rename_exe = "podman"}

###############
# Security
###############
trivy = "latest"

###############
# IAC
###############
opentofu = "latest"
terraform = "latest"
terragrunt = "latest"


###############
# Python items
###############

# llm install llm-github-copilot
# llm github_copilot auth login
"pipx:llm" = "latest"

uv = "latest"
