# Install Mise:
# curl https://mise.run | sh
# Activate: Put
# eval "$(mise activate bash)" in ~/.$bashrc
# eval "$(mise activate bash)" in ~/.$bashrc
#
# mise doctor
# mise plugins ls-remote
# mise plugins ls
# mise ls
# mise ls-remote java # to see the versions
# mise use java@21
# mise use k9s
# mise prune
# mise tool aws # check info about aws
#
# mise use -g <optional package else it'll show fuzzy all packages> # to globally install and add to this file
# mise use <optional package else it'll show fuzzy all packages> # to install in the project to create config mise.toml
#
# mise up # Install all packages defined in the config
[plugins]
neovim = "https://github.com/richin13/asdf-neovim"

[settings]
experimental = false

# Add latency to mac terminal
disable_backends = ["vfox"]

[tools]
###############
# mise
###############
usage = "latest" # To generate completions.
"github:jdx/mise" = {version = "latest", exe = "~/.local/bin/mise"}

###############
# Cloud
###############
aws-cli = { version = "latest", symlink_bins = "true" }
localstack = "latest"
azure-cli = "latest"
"aqua:scaleway/scaleway-cli" = "latest"

# Tools
"github:zyedidia/eget" = "latest"
"github:rjshrjndrn/templater" = "latest"
"aqua:schollz/croc" = "latest"
opencode = "latest"
"asdf:neovim" = "nightly"
go = "latest"
jq = "latest"
yq = "latest"
ripgrep = "latest"

lazygit = "latest"
delta = "latest"
github-cli = "latest"

# terminal tools
direnv = "latest"
tmux = "latest"
atuin = "latest"
starship = "latest"
fzf = "latest"

###############
# k8s
###############
k9s = "latest"
stern = "latest"
kubectl = "latest"
k3d = "latest"
argo = "latest"
flux2 = "latest"
helm = "latest"
helm-diff = "latest"
kubeconform = "latest"
cilium-cli = "latest"

###############
# Container/VM
###############
lima = "latest"
podman = {version = "latest", rename_exe = "podman"}

###############
# Security
###############
trivy = "latest"
age = "latest"
gopass = "latest"
vals = "latest"
doppler = "latest"

###############
# IAC
###############
opentofu = "latest"
terraform = "latest"
terragrunt = "latest"
packer = "latest"


###############
# Python items
###############

# llm install llm-github-copilot
# llm github_copilot auth login
"pipx:llm" = "latest"

uv = "latest"
node = "latest"
pnpm = "latest"

###############
# LLM
###############

ollama = {version="latest", os=["mac"]}
