[tools]
aws = { version = "latest", symlink_bins = "true" }
"github:BurntSushi/ripgrep" = "latest"
"github:zyedidia/eget" = "latest"
k9s = "latest"
opencode = "latest"
opentofu = "latest"
python = "3"
