# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  mouseEvents: true
  theme:
    # Border color of focused window
    activeBorderColor:
      - red
      - bold
git:
  fetchAll: false
keybinding:
  universal:
    confirmInEditor: <c-y>
  commits:
    moveUpCommit: "K"
    moveDownCommit: "J"
    openInBrowser: "o"
