add_newline = false
command_timeout = 50 # terminate all commans before ms
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'


# If you want to show the custom first
# format = "$custom$all"

[kubernetes]
symbol = "⛵ "
style = "dim yellow"
disabled = false

[aws]
disabled = true

[git_branch]
symbol = "🌱 "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_status]
conflicted = "🎏"
# ahead = "🏎💨"
# behind = "😰"
# diverged = "😵"
untracked = "🤷"
stashed = "📦"
modified = "📝"
staged = '[++\($count\)](green)'
renamed = "👅"
deleted = "🗑 " 
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[gcloud]
disabled = true

# Show some random string
# [custom.machine]
# command = "echo 'home-machine'"
# when = true
# style = "bold blue"
# format = "[$output]($style) "
