add_newline = false
command_timeout = 50 # terminate all commans before
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[kubernetes]
symbol = "⛵ "
style = "dim yellow"
disabled = false

[aws]
disabled = true

[git_branch]
symbol = "🌱 "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_status]
conflicted = "🎏"
# ahead = "🏎💨"
# behind = "😰"
# diverged = "😵"
untracked = "🤷"
stashed = "📦"
modified = "📝"
staged = '[++\($count\)](green)'
renamed = "👅"
deleted = "🗑" 
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[gcloud]
disabled = true
