[global]
  quiet = false
  show_hash = false
  upgrade_only = true
  target = "~/apps/bin/"

["stern/stern"]
["derailed/k9s"]
["mikefarah/yq"]
  asset_filters = [ "yq_{{.OS}}_{{.Arch}}" ]
["zyedidia/eget"]
["linkerd/linkerd2"]
  target = "~/apps/bin/linkerd"
["grafana/grizzly"]
["localsend/localsend"]
["iann0036/iamlive"]
# ["sst/opencode"]
#   asset_filters = ["opencode-{{.OS}}-{{.Arch}}.zip"]
