# To get the proper key names
# `keyd -m`
# [global]
# overload_tap_timeout = 200

[ids]


*
-2808:0101
-2808:0101
-4658:*
-feed:4658
-093A:0255

# zsa
-3297:1977
# device added 2808:0101 FTCS1000:00 2808:0101 Mouse (/dev/input/event7)
# device added: 2808:0101 FTCS1000:00 2808:0101 Touchpad (/dev/input/event8)

[main]

# Maps capslock to escape when pressed and control when held.
# capslock = overload(control, esc)
capslock = overload(nav, esc)
leftcontrol = overload(nav, esc)
#esc = overload(nav, esc)

a = lettermod(arrow, a, 150, 200)
s = lettermod(symbols, s, 150, 180) # lettermod is not working for typing and -
t = lettermod(terminal, t, 150, 200)
#a = overloadt(arrow, a, 250)
#tab = overloadt2(supertab, tab, 200)

[supertab]
r = macro(leftcontrol+leftshift+r) 

[arrow]
u = macro(leftalt+tab)
i = macro(leftmeta+space)
j = down
l = right
h = left
k = up


# Remaps the escape key to capslock
#esc = capslock

[nav:C]

# VIM shortcuts
' = macro(:q! enter)
; = macro(:w enter)
/ = macro(:q enter)

[alt]
# Workaround for gnome wayland
#m = macro(leftmeta k i t t y enter)

# ref: https://www.reddit.com/r/AsahiLinux/comments/1fj9xvt/my_maclike_keybindings_config_keyd/
# copy
c = C-insert
# Paste
v = S-insert
# Cut
x = S-delete
g = macro(set space -o space vi enter)
u = macro(sudo space su space - space ubuntu  enter)

# Media
n = nextsong
p = previoussong
space = playpause

#s = left
#d = down
#f = right
#e = up
j = down
l = right
h = left
k = up

[symbols]
s = s
h = +
l = -
; = =
j = [
k = ]
y = &
u = (
i = )
o = {
p = }
g = $
f = *
d = ^
, = "
. = _

[terminal]
t = t
j = macro(leftcontrol+f -)
l = macro(leftcontrol+f \\)
