apiVersion: k3d.io/v1alpha5
image: rancher/k3s:v1.25.6-k3s1
kind: Simple
kubeAPI:
  hostIP: 0.0.0.0
  hostPort: "16443"
metadata:
  name: my-cluster
options:
  kubeconfig:
    updateDefaultKubeconfig: false    # Update default kubeconfig with new cluster details
    switchCurrentContext: false       # Set the new cluster as the current context
  k3d:
    disableImageVolume: false
    disableLoadbalancer: false
    disableRollback: false
    loadbalancer: {}
    timeout: 60000000000
    wait: true
  k3s:
    extraArgs:
    - arg: --disable=traefik
      nodeFilters:
      - server:*
  runtime:
    HostPidMode: false
registries: {}
servers: 1
