name = "send-rjsh"
main = "src/index.js"
compatibility_date = "2024-01-01"

[durable_objects]
bindings = [
  { name = "RELAY", class_name = "StreamRelay" }
]

[[migrations]]
tag = "v1"
new_classes = ["StreamRelay"]
