auto_sync = true
history_filter = [
  "^llm",
  "^secret-cmd",
  "^innocuous-cmd .*--secret=.+",
  "^AWS_SECRET_ACCESS_KEY=.*",
  "^AWS_ACCESS_KEY_ID=.*",
  "^export AWS_SECRET_ACCESS_KEY=.*",
  "^export AWS_ACCESS_KEY_ID=.*",
  "^aws configure.*",
  ".*tmate.io.*",
  "^mfa",
]
secrets_filter = true
enter_accept = true
[stats]
[keys]
[sync]
records = true
[preview]
[daemon]
enabled = true
