#! /bin/sh

pkill -9 sxhkd && sxhkd &
# pkill -9 dunst && dunst &

killall -q polybar ; polybar -r mainbar &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          6
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefoxdeveloperedition desktop=^2 follow=on
bspc rule -a Slack desktop=^3 follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
feh --bg-center ~/Pictures/zoro.jpg
